[package]

name = "screenshot"
version = "0.0.3"
authors = ["Alex <alexchandel@gmail.com>"]
description = "Get a bitmap image of any display."
keywords = ["graphics", "image"]
repository = "https://github.com/alexchandel/screenshot-rs"
readme = "README.md"
license = "Unlicense"


[dev-dependencies.bmp]
bmp = "0.0.5"

[dev-dependencies.image]
image = "*"
